### ISSUE TITLE
Unit tests based on new launch API

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/launch#127]
While porting some ROS 1 packages to ROS 2 I wanted to also migrate the `rostest`s. Currently there is no API yet in `launch_testing` (beside the legacy API).

I tried two different approaches - the idea would be to move the "generic" stuff from one of these prototypes into `launch_testing` in order to be able to reuse it across tests:

1. Creating custom classes for the `LaunchDescription` as well as the `LaunchService` (https://github.com/GT-RAIL/async_web_server_cpp/pull/12/commits/1dad9c5ae6d4ca7521a5d7f6914d9b4231acd1cd). In this case the whole launch file uses those custom classes instead of the original ones. The custom description contains the logic for the return code handling and shutting down. The custom service contains the logic to use the return codes from the test actions as the global return code.

  The downside of this approach is that requires the launch file specifically being written for testing (by using these custom classes).

2. A custom class (`LaunchTestService`) is used in addition to the normal launch entities and the actions which are tests are being registered at that class and the class also wraps the `run` invocation on the "normal" launch service: (https://github.com/GT-RAIL/async_web_server_cpp/pull/12/commits/fc6f35adc5cb785a7b4234b32426c0a12fccbd74)

Any kind of feedback is highly appreciated.

**Comment by mjcarroll** [comment]
Looking at the two approaches, I think I would be partial to the second as it would keep the bulk of the test file consistent with the launch file.  I believe this would allow for more reuse and less boilerplate.
