### ISSUE TITLE
Add actions for running gtest and pytests

### ISSUE THREAD

**Issue by ivanpauno** [ros2/launch#176]
## Feature request
Add two actions, PyTest and GTest, to launch tests. See #161.

#### Feature description
Both of the actions will take two arguments:
- path: Path of the test to execute.
- timeout: float [seconds], indicating after how much time the test is killed.

Example usage will be like: https://github.com/ros2/launch/blob/5518345495df34ec11c4767a0d777811edce152d/launch_testing/examples/test_pub_sub_launch.py#L74-L83
Other frameworks could be added using the same parameters.

#### Implementation considerations
- It will use an underlying timeout mechanism of the test framework if it exists. If not, it will use a TimerAction for killing it.
- It will wrap the testing framework details (e.g. command line arguments).
- In a first iteration, it will not handle substitutions.

Proposed steps would be:
1. [x] Add a GTest action.
2. [x] Add a PyTest action.
3. [x] Add substitution support to GTest.
4. [x] Add substitution support to PyTest.

**Comment by hidmic** [comment]
Addressed by #178.
