### ISSUE TITLE
[launch_ros] use a custom context to avoid interferring with user init/shutdown of rclpy

### ISSUE THREAD

**Issue by wjwwood** [ros2/launch#189]
#### Feature description

Right now `launch_ros` (or more specifically `ros2 launch`) will init rclpy, create a node, and then later shutdown rclpy. It also expects that shutdown is not called prematurely.

If the user did their own init or shutdown, it might interfere with this. So `launch_ros` should instead use a custom context and do its own init and shutdown there.

**Comment by pbaughman** [comment]
@wjwwood I actually have a version of this done, but I'm waiting for ros2 crystal internally to test it (the version we have doesn't let you pass arguments to init yet).  I will push it for review, but I haven't been able to test it yet

**Comment by wjwwood** [comment]
That would be great!

**Comment by wjwwood** [comment]
This was done in #193.
