### ISSUE TITLE
options to rotate log files

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/launch#230]
There should be options to rotate the log files based on either of the following criteria:

* maximum size of a log file (e.g. 100MB)
* maximum duration of a log file (e.g. 24h)

**Comment by hidmic** [comment]
@dirk-thomas it's either but not both, right?

**Comment by dirk-thomas** [comment]
Implementation wise I don't see a reason why specifying both at the same time should be any more difficult. In that case we don't have to restrict it to either or.

**Comment by hidmic** [comment]
Well, for either I can use existing logging handlers, for both I need to roll out a custom one.

**Comment by dirk-thomas** [comment]
Ok, that is a good enough reason to only allow either or for now :+1:
