### ISSUE TITLE
DeprecationWarning: The loop argument is deprecated since Python 3.8

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/launch#387]
And scheduled for removal in Python 3.10.

E.g. https://github.com/ros2/launch/blob/f243fc6b3bcd276c194151e6933cda90761b1944/launch/launch/actions/timer_action.py#L84

**Comment by dirk-thomas** [comment]
Instead of creating separate tickets for each deprecation warning I will add more here:

* `launch_testing/test/launch_testing/test_launch_test_runner_validation.py:15`:

  > DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

**Comment by zmk5** [comment]
I submitted a fix for the second deprecation warning. I'm still trying to figure out what the deprecation in the first one is.

**Comment by zmk5** [comment]
Just checked. It actually didn't work for me. I'll try and fix the issue.

**Comment by zmk5** [comment]
Hey @dirk-thomas I have resolved all deprecation warnings associated with this issue. The team has also reviewed and merged the changes. You can close this issue if you would like 😄

**Comment by ivanpauno** [comment]
Thanks for your contribution @zmk5 !!!
