### ISSUE TITLE
[launch_testing] Revisit launch_testing | pytest integration

### ISSUE THREAD

**Issue by hidmic** [ros2/launch#405]
#### Feature description
The current [shim](https://github.com/ros2/launch/tree/9e0d841fe7969e765b0ad873fdb37837ca49d46d/launch_testing/launch_testing/pytest) that enables launch tests to be run under `pytest` is feature-limited and brittle (e.g. https://github.com/ros2/launch/pull/404). There's not true integration, but delegation from one testing framework to the other. Considering `launch_testing` itself would greatly benefit from existing `pytest` features, we should revisit this work.

**Comment by clalancette** [comment]
I'm going to argue we actually did this with the `launch_pytest` work, even though we aren't using that everywhere yet.  So I'm going to close this one out; feel free to reopen if you disagree.
