### ISSUE TITLE
ros2 node list lists 2 nodes of the same name and type after launching

### ISSUE THREAD

**Issue by ddengster** [ros2/launch#411]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 1804
- Installation type:
  - Source
- Version or commit hash:
  - Head

#### Steps to reproduce issue
Follow something similar to https://answers.ros.org/question/344141/ros2-launch-creates-two-nodes-of-same-type/

#### Expected behavior
Only 1 node should be launched when doing `ros2 node list`. 

#### Actual behavior
2 nodes listed on `ros2 node list` with the same name. This also confuses parameter retrieval - like I'll get another different value despite having set it already.

#### Additional information
Removing the `node_name`(or in later versions `name`) argument from the launch file seems to fix it.
https://answers.ros.org/question/344141/ros2-launch-creates-two-nodes-of-same-type/

**Comment by hidmic** [comment]
I've replied to those answer.ros.org questions. This seems connected to https://github.com/ros2/geometry2/issues/124 and it's not an issue with `geometry2` or `launch`, but with `robot_localization` and/or user code.

**Comment by 130s** [comment]
> I've replied to those answer.ros.org questions. This seems connected to [ros2/geometry2#124](https://github.com/ros2/geometry2/issues/124) and it's not an issue with `geometry2` or `launch`, but with `robot_localization` and/or user code.

I'm seeing the similar/same issue, in my program none of those packages you mentioned are involved. Ticketed https://github.com/ros2/launch/issues/704
