### ISSUE TITLE
Files in example_processes missing `.py` extension

### ISSUE THREAD

**Issue by rotu** [ros2/launch#423]
The following Python files are missing the `.py` extension:

* launch_testing/example_processes/exit_code_proc
* launch_testing/example_processes/good_proc
* launch_testing/example_processes/terminating_proc

Since they are never invoked "naked" (e.g. always as `python3 /path/to/script`) there is no benefit to leaving off the `.py` extension to make them look like a native executable.

_Discovered in https://github.com/ament/ament_cmake/issues/213#issuecomment-631129869_

**Comment by sloretz** [comment]
Thanks for reporting @rotu! Would you be willing to open a PR with a fix?

**Comment by rotu** [comment]
@sloretz I'm trying not to open PRs for stuff like this that's off-task (hence this issue instead of a PR).

@pbaughman is listed as the package maintainer. Maybe he can help?

**Comment by pbaughman** [comment]
Hi @rotu, I'm not currently working with the company who hired me to work on ROS2 testing.  It's OK for you to go ahead and make the change.
