### ISSUE TITLE
[launch] test_execute_process.test_execute_process_shutdown sometimes fails

### ISSUE THREAD

**Issue by ivanpauno** [ros2/launch#503]
## Bug report

**Required Info:**

- Operating System:
  - macOS, other platforms might be affected as well
- Installation type:
  - source
- Version or commit hash:
  - https://github.com/ros2/launch/commit/3a5c9df2e384271637ac029f48f020b7916498d6
- DDS implementation:
  - N/A
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

Run `test_execute_process`.

#### Expected behavior

It should never fail.

#### Actual behavior

It sometimes fail.

#### Additional information

Failure found in CI:

* https://ci.ros2.org/view/nightly/job/nightly_osx_repeated/2284/testReport/junit/launch.test.launch/test_execute_process/test_execute_process_shutdown_3_3_/

That's the only instance of the issue I've seen.

**Comment by sloretz** [comment]
I'm able to reproduce this when running

```
stress --cpu `nproc`
```
