### ISSUE TITLE
Feature request: make timeout from launch_testing's process_start configurable

### ISSUE THREAD

**Issue by MarcoLm993** [ros2/launch#519]
#### Feature description
Right now launch_tests wait only 15 seconds from the time the last process starts and the ReadyToTest action gets called.
This value is hard-coded in launch_testing and can be found [here](https://github.com/ros2/launch/blob/master/launch_testing/launch_testing/test_runner.py#L184).
Even though most times this timeout is large enough, there might be some larger systems that take longer to get ready before the actual test is ready to be executed. In those cases the whole test will fail saying `Timed out waiting for processes to start up`.

It would be nice to have the possibility to configure the timeout from the command line, in order to set a larger one in case it is necessary.

**Comment by marekmlk** [comment]
Already implemented in #625 for rolling.

**Comment by MarcoLm993** [comment]
Then I guess this issue can be closed :)
