### ISSUE TITLE
:man_farmer: `test_invalid_launch_extension` and `test_invalid_parser_implementations` test failures in repeated jobs

### ISSUE THREAD

**Issue by Blast545** [ros2/launch#583]
## Bug report

**Required Info:**

- Operating System:
  - Windows, Linux
  - Installation type:
  - Source
- Version or commit hash:
  - `master`
- Client library (if applicable):
  - `launch`

#### Steps to reproduce issue
Run a CI job in any of the repeated jobs Tier 1 buildfarms. Latest ones in the buildfarm:
https://ci.ros2.org/view/nightly/job/nightly_linux_repeated/2532/
https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/1838/
https://ci.ros2.org/view/nightly/job/nightly_win_rep/2491/

#### Expected behavior
All tests pass.

#### Actual behavior
Various tests fail. In particular, the regressions stated in this PR pass consistently the first time the test run, but it fails the second and third time.

#### Additional information
This error was introduced with #572, can you take a look @sloretz ?

**Comment by sloretz** [comment]
So far, I think this is related in some way to how `pytest-repeat` repeats tests. If I run the whole colcon invocation multiple times, the test never fails. If I run the test using `--repeate-until-fail N`, then it fails consistently - the first test always passes and every test afterwards fails.
