### ISSUE TITLE
Is there a way in launch.py to use $(var arg) to pass text arguments from file A to file B?

### ISSUE THREAD

**Issue by miku54** [ros2/launch#621]
- Operating System:
  -Ubuntu20.04
- Version or commit hash:
  - Galactic

#### Steps to reproduce issue

```
ROS1 :
<launch>
<arg name="car_mode"  default="" />
  <node pkg="move_base" type="move_base" respawn="false" name="move_base" output="screen">
    <rosparam file="$(find catkin_ws)/costmap_params/param_$(arg car_mode)/teb_local_planner_params.yaml"  command="load"/>
  </node>
</launch>
```
How can I implement the function of param_$(arg car_mode) in ROS2?

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org.  You'll get a better answer, and the answer will be saved and searchable in the future.  Closing this one.
