### ISSUE TITLE
Request for Release in Humble

### ISSUE THREAD

**Issue by stefanscherzinger** [ros2/launch#654]
This is a follow-up of #650 which seems to have only covered Rolling

The respective Humble PR is not yet listed in [the rosdistro's PRs](https://github.com/ros/rosdistro/pulls?q=is%3Apr+launch+humble+in%3Atitle+) (the most recent one is from May 11) and the launch version still seems to be [1.0.2-1](https://github.com/ros/rosdistro/blob/master/humble/distribution.yaml#L1869).

---
Edit: I'm sorry if this is not the right place for opening this.

**Comment by ijnek** [comment]
@clalancette would you have the time to make the release please?

**Comment by clalancette** [comment]
Done in https://github.com/ros/rosdistro/pull/34982
