### ISSUE TITLE
Launch.py from another launcher

### ISSUE THREAD

**Issue by jesusramondovale** [ros2/launch#738]
How can I launch a launch.py file from another launch where I've got another nodes?

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.

**Comment by jesusramondovale** [comment]
Ok thank you!
