### ISSUE TITLE
Bug or feature? PushRosNamespace is not forwarded to managed actions

### ISSUE THREAD

**Issue by oKermorgant** [ros2/launch#743]
Hi,

It appears that actions that are somehow managed (not added to the `LaunchDescription` explicitly but through some event or composition) do not inherit properties of their manager.

Here is an example, where

- a talker is explicitly run in a namespace
- a listener is also run in a namespace, through a `GroupAction`
- another listener is run through an `OnProcessStart` event which is itself inside a `GroupAction` pushing the correct namespace

The first listener gets the topic fine while the other one is run outside the namespace of its own `EventHandler`.

It may not be a bug but the logic is somehow hard to process.

```
from launch_ros.actions import Node

from launch import LaunchDescription
from launch.actions import RegisterEventHandler
from launch.event_handlers import OnProcessStart
from launch.actions import GroupAction
from launch_ros.actions import PushRosNamespace


def generate_launch_description():

    talker_ns = 'some_ns'

    # runs in namespace
    talker = Node(package='demo_nodes_cpp', executable='talker', name='talker',
                  namespace = talker_ns)

    event = OnProcessStart(target_action=talker,
                           on_start=[Node(package='demo_nodes_cpp', executable='listener',
                                          name = 'handled_listener')])

    handler = RegisterEventHandler(event)

    # handler runs in namespace but resulting listener will not
    handled_listener = GroupAction([PushRosNamespace(talker_ns), handler])

    # runs in namespace
    base_listener = GroupAction([PushRosNamespace(talker_ns), Node(package='demo_nodes_cpp', executable='listener',name='base_listener')])

    return LaunchDescription([talker, handled_listener, base_listener])
```

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/simple-launch-approaching-event-handling/34715/1

**Comment by clalancette** [comment]
> This was discussed in a meeting and is believed to be working as intended.

Yes, agreed.

Just to add a bit more context, these groups are evaluated lazily, but at the time they are needed.  So in the original example, the GroupAction used in `handled_listener` is only open for as long as it takes to register the event.  The event might be handled much, much later, at which point the group isn't around any more.

Besides explicitly adding in the namespace as @moriarty showed, you could also use the GroupAction in the `on_start` parameter to the `OnProcessStart` handler.
