### ISSUE TITLE
[Question] - How to configure sigterm_timeout/sigkill_timeout for a node

### ISSUE THREAD

**Issue by firesurfer** [ros2/launch#795]
I have a specific node that takes longer for shutdown therefore I would like to increase the timeout.

I couldn't find a way in a python launch file to set the timeout for a node. 
If I interpret: https://github.com/ros2/launch/pull/667 correctly it is only possible to set the timeout for a `ExecuteProcess` element but not for a `Node`.

**Comment by sloretz** [comment]
[`Node` inherits from `ExecuteProcess`](https://github.com/ros2/launch_ros/blob/38152b2d04c6b6f126d31726ac9e12888b2e2e1f/launch_ros/launch_ros/actions/node.py#L113). Anything that works for `ExecuteProcess` should also work for `Node`.
