### ISSUE TITLE
launch.xml args not be correctly identified

### ISSUE THREAD

**Issue by improve100** [ros2/launch#807]
I encountered the following problem when porting from Ros1 to Ros2. Is there anyone who can provide a better solution?

```
<arg name="tf_gnss_lidar" default="0.0 0.0 0.0 0.0 0.0 0.0"/>
<node pkg="tf2_ros" exec="static_transform_publisher" name="tf_gnss_lidar" args="$(var tf_gnss_lidar) /gnss /lidar"/> 
<node pkg="tf2_ros" exec="static_transform_publisher" name="tf_gnss_lidar" args="$(eval 'print(\'$(var tf_gnss_lidar)\')') /gnss /lidar" />
 
```
[ERROR] [1730867827.589323186] []: static_transform_publisher exited due to not having the right number of arguments

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
