### ISSUE TITLE
[Feedback desired] `ros2/ros2_documentation` tutorial on `launch_testing`

### ISSUE THREAD

**Issue by abaeyens** [ros2/launch#812]
Hi all, the current ROS 2 documentation site has two tutorials on unit testing but none on integration testing, so I wrote a tutorial covering the basics of using `launch_testing` for integration testing. Here's the PR: https://github.com/ros2/ros2_documentation/pull/4881.

While I've the impression I'm using `launch_testing` as intended, I'm not that experienced with this and I'd appreciate feedback from those more familiar with this package to ensure that the ROS 2 documentation aligns well with `launch_testing` best practices.

**Comment by clalancette** [comment]
I'm going to close this, as we are giving feedback on the PR.
